zuul:
  sslHostnameValidationEnabled: true
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitive-headers: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 600000
  IsSecure: false
  IsHostnameValidationRequired: false

spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 4096MB
  main:
    allow-bean-definition-overriding: true

server:
  port: 8765
  tomcat:
    max-http-post-size: -1

endpoints:
  routes:
    sensitive: false
